import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      {/* ↓↓ МИ ДОДАЛИ ЦЕЙ ТЕГ <head> ↓↓ */}
      <head>
        {/* Next.js автоматично додасть сюди вашу 'metadata'.
          А ми вручну додаємо скрипт для 3D/AR.
        */}
        <script 
          type="module" 
          src="https://ajax.googleapis.com/ajax/libs/model-viewer/3.5.0/model-viewer.min.js" 
          async>
        </script>
      </head>
      {/* ↑↑ КІНЕЦЬ ДОДАНОГО БЛОКУ ↑↑ */}

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <script src="//code.tidio.co/txssd0zgjsqnoyz0lrzkg0w5utbdipc9.js" async></script>
      </body>
    </html>
  );
}