export const products = [
  {
    id: "1",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/1.glb",
  },
  {
    id: "2",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/Furniture_Acoustics_Akunok-acoustic-sofa-1-seater.glb"
  },
  {
    id: "3",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Acoustics_Abstracta_dB-H-cubicle-desk-size-1800x800.glb",
  },
  {
    id: "4",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Z-Locker slanted 1200.glb",
  },
  {
    id: "5",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Bord Adjust.glb",
  },
  {
    id: "6",
    title: "Акустичний диван Akunok", 
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/Furniture_Office-Chairs_Gotessons_iQseat.glb" 
  },
  {
    id: "7",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Melvile-Chair.glb",
  },
  {
    id: "8",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Arkade Chair with upholstery.glb",
  },
  {
    id: "9",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Tables_Gotessons_Pocket-Table.glb",
  },
  {
    id: "10",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/Furniture_Chairs-Stools-Benches_Gotessons_Time-Out.glb"
  },
  {
    id: "11",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Shelving-Storage_AJ-Produkter_Compartment-Locker-Curve-1200mm-4-Sectio.glb",
  },
  {
    id: "12",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/okaybro.glb",
  },
  {
    id: "13",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/okaybro2.glb",
  },
  {
    id: "14",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/After_Chair.glb"
  },
  {
    id: "15",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/CM220_Monolit.glb",
  },
  {
    id: "16",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/pauline-comfort-bar-stool-75.glb",
  },
  {
    id: "17",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/pauline-comfort-bar-stool-65.glb",
  },
  {
    id: "18",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/pauline-bar-stool-75.glb"
  },
  {
    id: "19",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/pauline-bar-stool-65.glb",
  },
  {
    id: "20",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/ekko-chair.glb",
  },
  {
    id: "21",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/1.glb",
  },
  {
    id: "22",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/Furniture_Acoustics_Akunok-acoustic-sofa-1-seater.glb"
  },
  {
    id: "23",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Acoustics_Abstracta_dB-H-cubicle-desk-size-1800x800.glb",
  },
  {
    id: "24",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Z-Locker slanted 1200.glb",
  },
  {
    id: "25",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/1.glb",
  },
  {
    id: "26",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/Furniture_Acoustics_Akunok-acoustic-sofa-1-seater.glb"
  },
  {
    id: "27",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Acoustics_Abstracta_dB-H-cubicle-desk-size-1800x800.glb",
  },
  {
    id: "28",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Z-Locker slanted 1200.glb",
  },
  {
    id: "29",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/1.glb",
  },
  {
    id: "30",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/Furniture_Acoustics_Akunok-acoustic-sofa-1-seater.glb"
  },
  {
    id: "31",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Acoustics_Abstracta_dB-H-cubicle-desk-size-1800x800.glb",
  },
  {
    id: "32",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Z-Locker slanted 1200.glb",
  },
  {
    id: "33",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/1.glb",
  },
  {
    id: "34",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/Furniture_Acoustics_Akunok-acoustic-sofa-1-seater.glb"
  },
  {
    id: "35",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Acoustics_Abstracta_dB-H-cubicle-desk-size-1800x800.glb",
  },
  {
    id: "36",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Z-Locker slanted 1200.glb",
  },
  {
    id: "37",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/1.glb",
  },
  {
    id: "38",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/Furniture_Acoustics_Akunok-acoustic-sofa-1-seater.glb"
  },
  {
    id: "39",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Acoustics_Abstracta_dB-H-cubicle-desk-size-1800x800.glb",
  },
  {
    id: "40",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Z-Locker slanted 1200.glb",
  },
  {
    id: "41",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/1.glb",
  },
  {
    id: "42",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/Furniture_Acoustics_Akunok-acoustic-sofa-1-seater.glb"
  },
  {
    id: "43",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Acoustics_Abstracta_dB-H-cubicle-desk-size-1800x800.glb",
  },
  {
    id: "44",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Z-Locker slanted 1200.glb",
  },
  {
    id: "45",
    title: "Крісло 1",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/1.glb",
  },
  {
    id: "46",
    title: "Акустичний диван Akunok",
    price: 25000.00,
    category: "Дивани",
    description: "Акустичний диван/крісло для офісних просторів.",
    image: "office_chair.png",
    arModel: "/Furniture_Acoustics_Akunok-acoustic-sofa-1-seater.glb"
  },
  {
    id: "47",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Acoustics_Abstracta_dB-H-cubicle-desk-size-1800x800.glb",
  },
  {
    id: "48",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Z-Locker slanted 1200.glb",
  },
  {
    id: "49",
    title: "3",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Furniture_Acoustics_Abstracta_dB-H-cubicle-desk-size-1800x800.glb",
  },
  {
    id: "50",
    title: "4",
    price: 1000.00,
    category: "Стільці",
    description: "Комфортне підвісне крісло-гойдалка для вашої тераси. Приміряйте в AR.",
    image: "/goydalka.png",
    arModel: "/Z-Locker slanted 1200.glb",
  }
];

export function getAllProducts() {
  return products;
}

// 3. Функція для отримання одного товару за ID (без змін)
export function getProductById(id) {
  return products.find(product => product.id == id);
}

// 4. ФУНКЦІЯ ДЛЯ ОТРИМАННЯ КАТЕГОРІЙ (ОНОВЛЕНО)
export function getCategories() {
  const categories = products.map(p => p.category);
  // ↓↓ ЗМІНА ТУТ: Ми прибрали "Всі", список тепер "чистий" ↓↓
  return [...new Set(categories.filter(Boolean))];
}