// Шлях: lib/data.js

// 1. ВАША "ТАБЛИЦЯ" ТОВАРІВ - 50 ПОЗИЦІЙ
export const products = [
  // --- Шафи (1-10) ---
  {
    id: "1",
    title: "Мінімалістична шафа 'Nordic'",
    price: 320.00,
    category: "Шафи",
    description: "Чисті лінії та натуральне дерево. Ідеально для сучасного інтер'єру.",
    image: "https://placehold.co/600x400/E0E0E0/424242?text=Шафа+Nordic",
    arModel: null,
  },
  {
    id: "2",
    title: "Велика шафа-купе 'Loft'",
    price: 550.00,
    category: "Шафи",
    description: "Містка шафа з металевими елементами у стилі лофт.",
    image: "https://placehold.co/600x400/E0E0E0/424242?text=Шафа+Loft",
    arModel: null,
  },
  {
    id: "3",
    title: "Вузька шафа 'Solo'",
    price: 180.00,
    category: "Шафи",
    description: "Ідеальне рішення для невеликих приміщень та коридорів.",
    image: "https://placehold.co/600x400/E0E0E0/424242?text=Шафа+Solo",
    arModel: null,
  },
  {
    id: "4",
    title: "Відкрита шафа 'Grid'",
    price: 210.00,
    category: "Шафи",
    description: "Стелажна система для книг, декору або одягу.",
    image: "https://placehold.co/600x400/E0E0E0/424242?text=Шафа+Grid",
    arModel: null,
  },
  {
    id: "5",
    title: "Дитяча шафа 'Joy'",
    price: 260.00,
    category: "Шафи",
    description: "Яскраві кольори та безпечні матеріали для дитячої кімнати.",
    image: "https://placehold.co/600x400/E0E0E0/424242?text=Шафа+Joy",
    arModel: null,
  },
  {
    id: "6",
    title: "Шафа з дзеркалом 'Mirror'",
    price: 410.00,
    category: "Шафи",
    description: "Функціональна шафа з великим дзеркалом на весь зріст.",
    image: "https://placehold.co/600x400/E0E0E0/424242?text=Шафа+Mirror",
    arModel: null,
  },
  {
    id: "7",
    title: "Кутова шафа 'Angle'",
    price: 490.00,
    category: "Шафи",
    description: "Ефективно використовує простір у кутку кімнати.",
    image: "https://placehold.co/600x400/E0E0E0/424242?text=Шафа+Angle",
    arModel: null,
  },
  {
    id: "8",
    title: "Шафа-вітрина 'Glass'",
    price: 340.00,
    category: "Шафи",
    description: "Шафа зі скляними дверцятами для посуду або колекцій.",
    image: "https://placehold.co/600x400/E0E0E0/424242?text=Шафа+Glass",
    arModel: null,
  },
  {
    id: "9",
    title: "Шафа 'Classic Oak'",
    price: 480.00,
    category: "Шафи",
    description: "Класичний дизайн з масиву дуба.",
    image: "https://placehold.co/600x400/E0E0E0/424242?text=Шафа+Oak",
    arModel: null,
  },
  {
    id: "10",
    title: "Модульна шафа 'Flex'",
    price: 600.00,
    category: "Шафи",
    description: "Створіть власну конфігурацію з окремих модулів.",
    image: "https://placehold.co/600x400/E0E0E0/424242?text=Шафа+Flex",
    arModel: null,
  },

  // --- Столи (11-20) ---
  {
    id: "11",
    title: "Робочий стіл 'Focus'",
    price: 190.00,
    category: "Столи",
    description: "Простий та функціональний стіл для домашнього офісу.",
    image: "https://placehold.co/600x400/E2E8F0/4A5568?text=Стіл+Focus",
    arModel: null,
  },
  {
    id: "12",
    title: "Обідній стіл 'Gather'",
    price: 420.00,
    category: "Столи",
    description: "Великий стіл для всієї родини, масив ясена.",
    image: "https://placehold.co/600x400/E2E8F0/4A5568?text=Стіл+Gather",
    arModel: null,
  },
  {
    id: "13",
    title: "Кавовий столик 'Centro'",
    price: 110.00,
    category: "Столи",
    description: "Елегантний кавовий столик зі скляною поверхнею.",
    image: "https://placehold.co/600x400/E2E8F0/4A5568?text=Столик+Centro",
    arModel: null,
  },
  {
    id: "14",
    title: "Стіл-трансформер 'Flip'",
    price: 310.00,
    category: "Столи",
    description: "Змінює висоту з журнального на обідній.",
    image: "https://placehold.co/600x400/E2E8F0/4A5568?text=Стіл+Flip",
    arModel: null,
  },
  {
    id: "15",
    title: "Приставний столик 'Side'",
    price: 75.00,
    category: "Столи",
    description: "Маленький столик для дивану або ліжка.",
    image: "https://placehold.co/600x400/E2E8F0/4A5568?text=Столик+Side",
    arModel: null,
  },
  {
    id: "16",
    title: "Стіл 'Industrial Pipe'",
    price: 280.00,
    category: "Столи",
    description: "Стіл у стилі індастріал з металевими ніжками-трубами.",
    image: "https://placehold.co/600x400/E2E8F0/4A5568?text=Стіл+Pipe",
    arModel: null,
  },
  {
    id: "17",
    title: "Кухонний стіл 'Bistro'",
    price: 160.00,
    category: "Столи",
    description: "Компактний круглий стіл для двох.",
    image: "https://placehold.co/600x400/E2E8F0/4A5568?text=Стіл+Bistro",
    arModel: null,
  },
  {
    id: "18",
    title: "Стіл для переговорів 'Forum'",
    price: 650.00,
    category: "Столи",
    description: "Великий стіл для офісних конференц-залів.",
    image: "https://placehold.co/600x400/E2E8F0/4A5568?text=Стіл+Forum",
    arModel: null,
  },
  {
    id: "19",
    title: "Туалетний столик 'Grace'",
    price: 220.00,
    category: "Столи",
    description: "Витончений столик з дзеркалом для спальні.",
    image: "https://placehold.co/600x400/E2E8F0/4A5568?text=Столик+Grace",
    arModel: null,
  },
  {
    id: "20",
    title: "Стіл-консоль 'Entry'",
    price: 130.00,
    category: "Столи",
    description: "Вузький стіл для прихожої.",
    image: "https://placehold.co/600x400/E2E8F0/4A5568?text=Стіл+Entry",
    arModel: null,
  },

  // --- Стільці (21-30) ---
  {
    id: "21",
    title: "Стілець 'Scandi'",
    price: 85.00,
    category: "Стільці",
    description: "Класичний скандинавський дизайн, дерев'яні ніжки.",
    image: "https://placehold.co/600x400/F0F4F8/4A5568?text=Стілець+Scandi",
    arModel: null,
  },
  {
    id: "22",
    title: "Офісне крісло 'Ergo'",
    price: 240.00,
    category: "Стільці",
    description: "Ергономічне крісло з підтримкою спини.",
    image: "https://placehold.co/600x400/F0F4F8/4A5568?text=Крісло+Ergo",
    arModel: null,
  },
  {
    id: "23",
    title: "Барний стілець 'High'",
    price: 110.00,
    category: "Стільці",
    description: "Високий стілець для барної стійки.",
    image: "https://placehold.co/600x400/F0F4F8/4A5568?text=Стілець+High",
    arModel: null,
  },
  {
    id: "24",
    title: "Крісло 'Cocon'",
    price: 320.00,
    category: "Стільці",
    description: "М'яке затишне крісло для читання.",
    image: "https://placehold.co/600x400/F0F4F8/4A5568?text=Крісло+Cocon",
    arModel: null,
  },
  {
    id: "25",
    title: "Стілець 'Wire'",
    price: 95.00,
    category: "Стільці",
    description: "Сучасний дизайн з металевого дроту.",
    image: "https://placehold.co/600x400/F0F4F8/4A5568?text=Стілець+Wire",
    arModel: null,
  },
  {
    id: "26",
    title: "Розкладний стілець 'Fold'",
    price: 40.00,
    category: "Стільці",
    description: "Практичний стілець, який легко зберігати.",
    image: "https://placehold.co/600x400/F0F4F8/4A5568?text=Стілець+Fold",
    arModel: null,
  },
  {
    id: "27",
    title: "Табурет 'Dot'",
    price: 35.00,
    category: "Стільці",
    description: "Простий дерев'яний табурет.",
    image: "https://placehold.co/600x400/F0F4F8/4A5568?text=Табурет+Dot",
    arModel: null,
  },
  {
    id: "28",
    title: "Крісло-гойдалка 'Rock'",
    price: 190.00,
    category: "Стільці",
    description: "Сучасна інтерпретація крісла-гойдалки.",
    image: "https://placehold.co/600x400/F0F4F8/4A5568?text=Крісло+Rock",
    arModel: null,
  },
  {
    id: "29",
    title: "Стілець 'Velvet'",
    price: 130.00,
    category: "Стільці",
    description: "Елегантний стілець з оксамитовою (velvet) оббивкою.",
    image: "https://placehold.co/600x400/F0F4F8/4A5568?text=Стілець+Velvet",
    arModel: null,
  },
  {
    id: "30",
    title: "Крісло-мішок 'Bean'",
    price: 80.00,
    category: "Стільці",
    description: "Безкаркасне крісло для відпочинку.",
    image: "https://placehold.co/600x400/F0F4F8/4A5568?text=Крісло+Bean",
    arModel: null,
  },

  // --- Меблі для ванни (31-40) ---
  {
    id: "31",
    title: "Тумба під умивальник 'Aqua'",
    price: 230.00,
    category: "Меблі для ванни",
    description: "Вологостійка тумба з двома шухлядами.",
    image: "https://placehold.co/600x400/EBF8FF/2C5282?text=Тумба+Aqua",
    arModel: null,
  },
  {
    id: "32",
    title: "Дзеркальна шафа 'Reflect'",
    price: 170.00,
    category: "Меблі для ванни",
    description: "Шафа з дзеркальними дверцятами та підсвіткою.",
    image: "https://placehold.co/600x400/EBF8FF/2C5282?text=Шафа+Reflect",
    arModel: null,
  },
  {
    id: "33",
    title: "Пенал для ванної 'Tower'",
    price: 190.00,
    category: "Меблі для ванни",
    description: "Висока та вузька шафа для рушників та косметики.",
    image: "https://placehold.co/600x400/EBF8FF/2C5282?text=Пенал+Tower",
    arModel: null,
  },
  {
    id: "34",
    title: "Полиця 'Splash'",
    price: 50.00,
    category: "Меблі для ванни",
    description: "Скляна полиця з нержавіючими кріпленнями.",
    image: "https://placehold.co/600x400/EBF8FF/2C5282?text=Полиця+Splash",
    arModel: null,
  },
  {
    id: "35",
    title: "Тумба 'Zen' (бамбук)",
    price: 150.00,
    category: "Меблі для ванни",
    description: "Екологічна тумба з натурального бамбука.",
    image: "https://placehold.co/600x400/EBF8FF/2C5282?text=Тумба+Zen",
    arModel: null,
  },
  {
    id: "36",
    title: "Підвісна тумба 'Air'",
    price: 280.00,
    category: "Меблі для ванни",
    description: "Сучасна підвісна конструкція, ефект 'невагомості'.",
    image: "https://placehold.co/600x400/EBF8FF/2C5282?text=Тумба+Air",
    arModel: null,
  },
  {
    id: "37",
    title: "Стелаж 'Ladder'",
    price: 90.00,
    category: "Меблі для ванни",
    description: "Стелаж-драбина для рушників.",
    image: "https://placehold.co/600x400/EBF8FF/2C5282?text=Стелаж+Ladder",
    arModel: null,
  },
  {
    id: "38",
    title: "Шафа 'Spa'",
    price: 210.00,
    category: "Меблі для ванни",
    description: "Компактна шафка для зберігання.",
    image: "https://placehold.co/600x400/EBF8FF/2C5282?text=Шафа+Spa",
    arModel: null,
  },
  {
    id: "39",
    title: "Умивальник з тумбою 'Mono'",
    price: 450.00,
    category: "Меблі для ванни",
    description: "Готове рішення: литий умивальник та тумба.",
    image: "https://placehold.co/600x400/EBF8FF/2C5282?text=Умивальник+Mono",
    arModel: null,
  },
  {
    id: "40",
    title: "Кошик для білизни 'Linen'",
    price: 65.00,
    category: "Меблі для ванни",
    description: "Плетений кошик з текстильним вкладишем.",
    image: "https://placehold.co/600x400/EBF8FF/2C5282?text=Кошик+Linen",
    arModel: null,
  },

  // --- Полиці (41-50) ---
  {
    id: "41",
    title: "Настінна полиця 'Float'",
    price: 45.00,
    category: "Полиці",
    description: "Мінімалістична полиця з прихованим кріпленням.",
    image: "https://placehold.co/600x400/EDF2F7/2D3748?text=Полиця+Float",
    arModel: null,
  },
  {
    id: "42",
    title: "Книжкова полиця 'Cube'",
    price: 130.00,
    category: "Полиці",
    description: "Набір квадратних полиць-модулів.",
    image: "https://placehold.co/600x400/EDF2F7/2D3748?text=Полиця+Cube",
    arModel: null,
  },
  {
    id: "43",
    title: "Стелаж 'Towering'",
    price: 280.00,
    category: "Полиці",
    description: "Високий 5-ярусний стелаж для книг.",
    image: "https://placehold.co/600x400/EDF2F7/2D3748?text=Стелаж+Towering",
    arModel: null,
  },
  {
    id: "44",
    title: "Кутова полиця 'Corner'",
    price: 60.00,
    category: "Полиці",
    description: "Ефективно використовує простір у кутку.",
    image: "https://placehold.co/600x400/EDF2F7/2D3748?text=Полиця+Corner",
    arModel: null,
  },
  {
    id: "45",
    title: "Полиця 'Industrial'",
    price: 110.00,
    category: "Полиці",
    description: "Полиця з дерева та металевих труб.",
    image: "https://placehold.co/600x400/EDF2F7/2D3748?text=Полиця+Industrial",
    arModel: null,
  },
  {
    id: "46",
    title: "Полиця для спецій 'Spice'",
    price: 30.00,
    category: "Полиці",
    description: "Вузька полиця для кухні.",
    image: "https://placehold.co/600x400/EDF2F7/2D3748?text=Полиця+Spice",
    arModel: null,
  },
  {
    id: "47",
    title: "Полиця 'Zig-Zag'",
    price: 90.00,
    category: "Полиці",
    description: "Дизайнерська настінна полиця.",
    image: "https://placehold.co/600x400/EDF2F7/2D3748?text=Полиця+Zig-Zag",
    arModel: null,
  },
  {
    id: "48",
    title: "Полиця для взуття 'Entry'",
    price: 70.00,
    category: "Полиці",
    description: "Низька полиця для взуття в прихожій.",
    image: "https://placehold.co/600x400/EDF2F7/2D3748?text=Полиця+Entry",
    arModel: null,
  },
  {
    id: "49",
    title: "Модульний стелаж 'Build'",
    price: 150.00,
    category: "Полиці",
    description: "Зберіть стелаж потрібного вам розміру.",
    image: "https://placehold.co/600x400/EDF2F7/2D3748?text=Стелаж+Build",
    arModel: null,
  },
  {
    id: "50",
    title: "Полиця 'Honey'",
    price: 85.00,
    category: "Полиці",
    description: "Набір гексагональних полиць (соти).",
    image: "https://placehold.co/600x400/EDF2F7/2D3748?text=Полиця+Honey",
    arModel: null,
  },
];

// 2. Функція для отримання всіх товарів (просто повертає масив)
export function getAllProducts() {
  return products;
}

// 3. Функція для отримання одного товару за ID
export function getProductById(id) {
  // Використовуємо '==' для "м'якого" порівняння, це надійно
  return products.find(product => product.id == id);
}

// 4. Функція для отримання всіх унікальних категорій
export function getCategories() {
  const categories = products.map(p => p.category);
  // Повертаємо унікальні значення + "Всі"
  // Додаємо .filter(Boolean), щоб ігнорувати можливі порожні категорії
  return ["Всі", ...new Set(categories.filter(Boolean))];
}